version: '3.8'
services:
  concordium-node:
    container_name: concordium-node
    image: "concordium-local-node:latest"
#   build:
#     context: ./node
#     dockerfile: Dockerfile
    ports:
#     - "8000:8000"
      - "10000:10000"
      - "11000:11000"
    volumes:
      - ./.docker-data/concordium-node:/root/workdir
